import { Editor } from '@tiptap/core';
import { allowBase64Images } from './extensions/images';
import { setupAddAnchorDialog } from './menu/addAnchorId';
import { setupAddLink } from './menu/addLink';
import { setupAlignment } from './menu/alignment';
import { setupCapitalizationMenu } from './menu/capitalizationMenu';
import { setupChecklist } from './menu/checkList';
import { setupClearFormatting } from './menu/clearFormatting';
import { setupFormatting } from './menu/formatting';
import { setupImageUpload } from './menu/images';
import { setupLists } from './menu/lists';
import { setupFontFamily } from './menu/setupFontFamily';
import { setupFontSize } from './menu/setupFontSize';
import { setupFormatPainter } from './menu/setupFormatPainter';
import { setupSearchReplace } from './menu/setupSearchReplace';
import { setupSpellcheckToggle } from './menu/spellCheck';
import { setupTableMenu } from './menu/tables';
import { setupTextColor } from './menu/textColorSetup';
import { setupUndoRedo } from './menu/undoRedo';
import { setupWordCount } from './menu/wordCount';
import { setupHeadingStyle } from './menu/heading';
import { superscriptSubscript } from './menu/superscriptSubscript';
import { addAdditionalButtons } from './menu/addAdditionalButton';
import { addEmojisAndCharacters } from './menu/addEmojisAndCharacters';
import { setupFullscreenToggle } from './menu/fullScreen';
import { showPreview } from './menu/showPreview'
import { setupHorizontalRule } from './menu/setupHorizontal';
import { textDirectionMenu } from './menu/textDirection';
import { pageBreakMenu } from './menu/pageBreakMenu';

export const initMenu = (editor: Editor, editorElement: HTMLDivElement) => {
    setupFormatting(editor);
    setupLists(editor);
    setupAlignment(editor);
    setupTableMenu(editor);
    setupImageUpload(editor, editorElement);
    setupUndoRedo(editor);
    setupClearFormatting(editor);
    setupFontSize(editor);
    setupFontFamily(editor);
    setupTextColor(editor);
    setupCapitalizationMenu(editor);
    setupWordCount(editor);
    setupChecklist(editor);
    setupSpellcheckToggle();
    setupSearchReplace(editor);
    setupFormatPainter(editor);
    setupAddAnchorDialog(editor);
    setupAddLink(editor);
    allowBase64Images(editor);
    setupHeadingStyle(editor);
    superscriptSubscript(editor);
    addAdditionalButtons(editor);
    setupAddLink(editor);
    addEmojisAndCharacters(editor);
    setupFullscreenToggle(editor);
    showPreview(editor);
    setupHorizontalRule(editor);
    textDirectionMenu(editor);
    pageBreakMenu(editor);
}
