import { Editor } from '@tiptap/core';
import { allowBase64Images } from '../extensions/images';
import { setupAddAnchorDialog } from './addAnchorId';
import { setupAddLink } from './addLink';
import { setupAlignment } from './alignment';
import { setupCapitalizationMenu } from './capitalizationMenu';
import { setupChecklist } from './checkList';
import { setupClearFormatting } from './clearFormatting';
import { setupFormatting } from './formatting';
import { setupImageUpload } from './images';
import { setupLists } from './lists';
import { setupFontFamily } from './setupFontFamily';
import { setupFontSize } from './setupFontSize';
import { setupFormatPainter } from './setupFormatPainter';
import { setupSearchReplace } from './setupSearchReplace';
import { setupSpellcheckToggle } from './spellCheck';
import { setupTableMenu } from './tables';
import { setupTextColor } from './textColorSetup';
import { setupUndoRedo } from './undeRedo';
import { setupWordCount } from './wordCount';
import { setupHeadingStyle } from './heading';
import { superscriptSubscript } from './superscriptSubscript';

export const initMenu = (editor: Editor) => {
    setupFormatting(editor);
    setupLists(editor);
    setupAlignment(editor);
    setupTableMenu(editor);
    setupImageUpload(editor);
    setupUndoRedo(editor);
    setupClearFormatting(editor);
    setupFontSize(editor);
    setupFontFamily(editor);
    setupTextColor(editor);
    setupCapitalizationMenu(editor);
    setupWordCount(editor);
    setupChecklist(editor);
    setupSpellcheckToggle();
    setupSearchReplace(editor);
    setupFormatPainter(editor);
    setupAddAnchorDialog(editor);
    setupAddLink(editor);
    allowBase64Images(editor);
    setupHeadingStyle(editor);
    superscriptSubscript(editor);
}
